Repository angelswing-team/volume-calculator-for-dsm, pull requests merged in 2018-08, with the labels that each got.

#5 [4] Revise Polygon clip testing condition
  src/calculate_volume.py
  src/clip.py
  src/main.py
Labels: bug

#6 Fix wrongly clipped tiff_arr
  src/clip.py
Labels: bug

#7 Add comments to explain the algorithm
  README.md
  src/clip.py
  src/extent_utils.py
  src/main.py
Labels: question

#9 Reproject the WKT geometry
  src/main.py
  src/wkt_geom_utils.py
Labels: enhancement
